multilib_global.bbclass: Avoid expanding native recipes in NON_MULTILIB_RECIPES
Fixed:
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "x86"
MACHINE = "qemux86-64"

$ bitbake lib32-grub-native
The build would go on before the patch which was incorrect. Now:

ERROR: Nothing PROVIDES 'lib32-grub-native'. Close matches:
[snip]

The nativesdk doesn't have such an issue, so only skip native.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>